services:
  nest_api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    restart: 'unless-stopped'
    ports:
      - 4400:4400
    env_file:
      - ./.env
    depends_on:
      - postgres_14
    networks:
      - app_network

  migration:
    build: .
    env_file:
      - ./.env
    command: './wait-for-it.sh nest_postgres:5432 -- yarn run migration:run'
    depends_on:
      - postgres_14

  postgres_14:
    image: postgres:14
    container_name: nest_postgres
    command: ['postgres', '-c', 'log_statement=all']
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce
    ports:
      - 5429:5432
    volumes:
      - ./mount-data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    name: app_network